[package]
name = "nimb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
ron = "0.8.1"
serde = { version = "1.0.183", features = ["derive" ]}
toml = "0.7.6"
